const Ly = [
    {
        id: "0",
        question: "Chọn câu đúng.",
        options: [
            "Cường độ dòng điện cho biết độ mạnh hay yếu của dòng điện.",
            "Khi nhiệt độ tăng thì cường độ dòng điện tăng.",
            "Cường độ dòng điện qua một đoạn mạch tỉ lệ nghịch với điện lượng dịch chuyển qua đoạn mạch.",
            "Dòng điện là dòng các electron dịch chuyển có hướng.",
        ],
        correct: "Cường độ dòng điện cho biết độ mạnh hay yếu của dòng điện.",
        image: "",
        slove_image: "Ly/1.png",
    },
    {
        id: "1",
        question: "Suất điện động của một acquy là 2 V, lực lạ đã thực hiện một công là 6 mJ. Lượng điện tích dịch chuyển khi đó là",
        options: ["18.10^–3 C.", "3.10^–3 C.", "0,5.10^–3 C.", "1,8.10^–3 C."],
        correct: "3.10^–3 C.",
        image: "",
        slove_image: "Ly/2.png",
    },
    {
        id: "2",
        question:
            "Đường đặc tuyến Vôn - Ampe biểu diễn sự phụ thuộc của cường độ dòng điện qua một điện trở vào hiệu điện thế hai đầu vật dẫn là đường",
        options: ["cong hình elip.", "thẳng.", "hyperbol.", "parabol."],
        correct: "thẳng.",
        image: "",
        slove_image: "Ly/3.png",
    },
    {
        id: "3",
        question:
            "Đặt vào hai đầu một điện trở R = 20 Ω một hiệu điện thế U = 2 V trong khoảng thời gian t = 20 s. Lượng điện tích di chuyển qua điện trở là",
        options: ["q = 4 C.", "q = 1 C.", "q = 2 C.", "q = 5 mC."],
        correct: "q = 2 C.",
        image: "",
        slove_image: "Ly/4.png",
    },
    {
        id: "4",
        question: "Dòng điện chạy qua dây dẫn của một camera có cường độ 50 μA. Số electron chạy qua dây dẫn mỗi giây là",
        options: ["3,75.10^14 hạt.", "3,35.10^14 hạt.", "3,125.10^14 hạt.", "50.10^15 hạt."],
        correct: "3,125.10^14 hạt.",
        image: "",
        slove_image: "Ly/5.png",
    },
    {
        id: "5",
        question: "Hệ số nhiệt điện trở α của kim loại phụ thuộc vào yếu tố nào sau đây?",
        options: [
            "Khoảng nhiệt độ và chế độ gia công của vật liệu đó.",
            "Độ sạch của kim loại và chế độ gia công của vật liệu đó.",
            "Độ sạch của kim loại.",
            "Khoảng nhiệt độ, độ sạch của kim loại và chế độ gia công của vật liệu đó.",
        ],
        correct: "Khoảng nhiệt độ, độ sạch của kim loại và chế độ gia công của vật liệu đó.",
        image: "",
        slove_image: "Ly/6.png",
    },
    {
        id: "6",
        question:
            "Cho mạch điện như hình vẽ. Suất điện động E = 28V, điện trở trong r = 2Ω, R = 5Ω. Độ lớn của cường độ dòng điện trong mạch chính là",
        options: ["2 A.", "3 A.", "4 A.", "5 A."],
        correct: "4 A.",
        image: "Ly/7.png",
        slove_image: "Ly/8.png",
    },
    {
        id: "7",
        question: "Câu nào sau đây là sai?",
        options: [
            "Suất điện động của nguồn điện là đại lượng đặc trưng cho khả năng sinh công của nguồn điện.",
            "Đơn vị công cũng là đơn vị suất điện động.",
            "Suất điện động của nguồn điện bằng công để di chuyển điện tích dương 1 C từ cực âm đến cực dương bên trong nguồn.",
            "Suất điện động được đo bằng thương số giữa công A của lực lạ để di chuyển một điện tích dương từ cực âm đến cực dương bên trong nguồn điện và độ lớn q của điện tích đó.",
        ],
        correct: "Suất điện động của nguồn điện bằng công để di chuyển điện tích dương 1 C từ cực âm đến cực dương bên trong nguồn.",
        image: "",
        slove_image: "Ly/9.png",
    },
    {
        id: "8",
        question: "Một đoạn mạch tiêu thụ có công suất 100 W, trong 10 phút nó tiêu thụ một năng lượng",
        options: ["2000 J.", "5 J.", "120 kJ.", "60 kJ."],
        correct: "60 kJ.",
        image: "",
        slove_image: "Ly/10.png",
    },
    {
        id: "9",
        question: "Công suất định mức của các dụng cụ điện là",
        options: [
            "công suất lớn nhất mà dụng cụ đó có thể đạt được.",
            "công suất tối thiểu mà dụng cụ đó có thể đạt được.",
            "công suất đạt được khi nó hoạt động bình thường.",
            "công suất trung bình của dụng cụ đó.",
        ],
        correct: "công suất đạt được khi nó hoạt động bình thường.",
        image: "",
        slove_image: "Ly/11.png",
    },
    {
        id: "10",
        question:
            "Hai điện tích điểm nằm yên trong chân không tương tác với nhau bằng một lực F. Thay đổi các điện tích thì lực tương tác đổi chiều nhưng độ lớn không đổi. Hỏi các yếu tố trên thay đổi như thế nào?",
        options: ["Đổi dấu q1, không thay đổi q2.", "Tăng giảm sao cho q1 + q2 không đổi.", "Đổi dấu q1 và q2.", "Tăng gấp đôi q1 giảm 2 lần q2."],
        correct: "Đổi dấu q1, không thay đổi q2.",
        image: "",
        slove_image: "Ly/12.png",
    },
    {
        id: "11",
        question: "Một dây dẫn kim loại có điện lượng q = 30 C đi qua tiết diện của dây trong 2 giây. Số electron qua tiết diện của dây trong 1s là",
        options: ["9,375.10^19 hạt.", "15,625.10^17 hạt.", "9,375.10^18 hạt.", "3,125.10^18 hạt."],
        correct: "9,375.10^19 hạt.",
        image: "",
        slove_image: "Ly/13.png",
    },
    {
        id: "12",
        question:
            "Đồ thị biểu diễn độ lớn lực tương tác giữa hai điện tích điểm trong chân không phụ thuộc vào khoảng cách r được cho như hình vẽ bên. Tính tỉ số F2/F1?",
        options: ["2.", "3.", "4.", "5."],
        correct: "4.",
        image: "",
        slove_image: "Ly/14.png",
    },
    {
        id: "13",
        question: "Công thức tính điện năng tiêu thụ của một đoạn mạch là",
        options: ["A = U.I.t.", "A = 3 Đề thi Học kì 2 Vật lí 11 Kết nối tri thức (có đáp án + ma trận)It.", "A = I.t / U.", "A = U.I / t."],
        correct: "A = U.I.t.",
        image: "",
        slove_image: "Ly/15.png",
    },
    {
        id: "14",
        question:
            "Hai điện tích điểm cùng độ lớn 10^-4C đặt trong chân không, để tương tác nhau bằng lực có độ lớn 10^-3C thì chúng phải đặt cách nhau",
        options: ["30000 m.", "300 m.", "90000 m.", "900 m."],
        correct: "300 m.",
        image: "",
        slove_image: "Ly/16.png",
    },
    {
        id: "15",
        question: "Thế năng của một electron tại điểm M trong điện trường của một điện tích điểm là -4,8.10^-19 (J). Điện thế tại M là",
        options: ["3,2 V.", "-3 V.", "2 V.", "3 V."],
        correct: "3 V.",
        image: "",
        slove_image: "Ly/17.png",
    },
    {
        id: "16",
        question: "Một tụ điện có điện dung là bao nhiêu thì tích lũy một năng lượng 0,015 J dưới một hiệu điện thế 5 V:",
        options: ["1,2.10^-2 F.", "1,2.10^-4 F.", "1,2.10^-3 F.", "12.10^-3 F."],
        correct: "1,2.10^-3 F.",
        image: "",
        slove_image: "Ly/18.png",
    },
    {
        id: "17",
        question:
            "Người ta treo hai quả cầu nhỏ khối lượng bằng nhau bằng hai sợi dây nhẹ có độ dài ℓ như nhau. Cho chúng nhiễm điện bằng nhau thì chúng đẩy nhau và cân bằng khi mỗi dây treo hợp với phương thẳng đứng một góc 15°. Tính sức căng của dây treo. Lấy g = 10 m/s^2.",
        options: ["520.10^-5 N.", "103,5.10^-5 N.", "261.10^-5 N.", "743.10^-5 N."],
        correct: "103,5.10^-5 N.",
        image: "Ly/19.png",
        slove_image: "Ly/20.png",
    },
    {
        id: "18",
        question: "Độ lớn cường độ điện trường tại một điểm gây bởi một điện tích điểm không phụ thuộc",
        options: [
            "độ lớn điện tích thử.",
            "độ lớn điện tích đó.",
            "khoảng cách từ điểm đang xét đến điện tích đó.",
            "hằng số điện môi của của môi trường.",
        ],
        correct: "độ lớn điện tích thử.",
        image: "",
        slove_image: "Ly/21.png",
    },
    {
        id: "19",
        question:
            "Một electron chuyển động dọc theo đường sức của một điện trường đều. Cường độ điện trường E = 200 (V/m) vận tốc ban đầu của electron là 3.10^5(m/s). Tại lúc vận tốc bằng không thì nó đã đi được đoạn đường bao nhiêu?",
        options: ["5,12 (mm).", "2,56 (mm).", "1,28 (mm).", "10,24 (mm)."],
        correct: "1,28 (mm).",
        image: "",
        slove_image: "Ly/22.png",
    },
    {
        id: "20",
        question: "Khi độ lớn điện tích thử đặt tại một điểm tăng lên gấp đôi thì điện thế tại điểm đó",
        options: ["không đổi.", "tăng gấp đôi.", "giảm một nửa.", "tăng gấp 4."],
        correct: "không đổi.",
        image: "",
        slove_image: "Ly/23.png",
    },
    {
        id: "21",
        question:
            "Nếu đặt vào hai đầu tụ một hiệu điện thế 4 V thì tụ tích được một điện lượng 2µC. Nếu đặt vào hai đầu tụ một hiệu điện thế 10 V thì tụ tích được một điện lượng",
        options: ["50µC.", "1µC.", "5µC", "0,8µC."],
        correct: "5µC",
        image: "",
        slove_image: "Ly/24.png",
    },
    {
        id: "22",
        question:
            "Cường độ điện trường gây ra bởi điện tích Q = 5.10^-9C, tại một điểm trong chân không cách điện tích một khoảng 30 cm có độ lớn là",
        options: ["E = 0,450 (V/m).", "E = 0,225 (V/m).", "E = 500 (V/m).", "E = 2250 (V/m)."],
        correct: "E = 500 (V/m).",
        image: "",
        slove_image: "Ly/25.png",
    },
    {
        id: "23",
        question: "Công của lực điện trường tác dụng lên một điện tích chuyển động từ M đến N sẽ",
        options: [
            "chỉ phụ thuộc vào vị trí điểm M không phụ thuộc vào vị trí điểm N.",
            "phụ thuộc vào hình dạng của đường đi MN.",
            "phụ thuộc vị trí các điểm M và N chứ không phụ thuộc vào đoạn MN dài hay ngắn.",
            "càng lớn khi đoạn đường MN càng dài.",
        ],
        correct: "phụ thuộc vị trí các điểm M và N chứ không phụ thuộc vào đoạn MN dài hay ngắn.",
        image: "",
        slove_image: "Ly/26.png",
    },
    {
        id: "24",
        question:
            "Ở sát mặt Trái Đất, vectơ cường độ điện trường hướng thẳng đứng từ trên xuống dưới và có độ lớn vào khoảng 150 V/m. Tính hiệu điện thế giữa một điểm ở độ cao 2,4 m và mặt đất.",
        options: ["720 (V).", "360 (V).", "120 (V).", "750 (V)."],
        correct: "360 (V).",
        image: "",
        slove_image: "Ly/27.png",
    },
    {
        id: "25",
        question: "Hai tụ điện chứa cùng một lượng điện tích thì",
        options: [
            "chúng phải có cùng điện dung.",
            "hiệu điện thế giữa hai bản của mỗi tụ điện phải bằng nhau.",
            "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản nhỏ hơn.",
            "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản lớn hơn",
        ],
        correct: "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản nhỏ hơn.",
        image: "",
        slove_image: "Ly/28.png",
    },
    {
        id: "26",
        question:
            "Hai điện tích q1 = 2.10^-6 C và q2 = -8.10^-6 C lần lượt đặt tại hai điểm A và B với AB = 10 (cm). Xác định điểm M trên đường AB mà tại đó E2 = 4E1",
        options: [
            "M nằm trong AB với AM = 2,5 (cm).",
            "M nằm trong AB với AM = 5 (cm).",
            "M nằm ngoài AB với AM = 2,5 (cm).",
            "M nằm ngoài AB với AM = 5 (cm).",
        ],
        correct: "M nằm ngoài AB với AM = 5 (cm).",
        image: "",
        slove_image: "Ly/29.png",
    },
    {
        id: "27",
        question: "Điều nào sau đây là sai khi nói về cấu tạo của tụ điện?",
        options: [
            "Hai bản của tụ là hai vật dẫn.",
            "Giữa hai bản của tụ có thể là chân không.",
            "Hai bản của tụ cách nhau một khoảng rất lớn.",
            "Giữa hai bản của tụ là điện môi.",
        ],
        correct: "Hai bản của tụ cách nhau một khoảng rất lớn.",
        image: "",
        slove_image: "Ly/30.png",
    },
    {
        id: "29",
        question: "Giữa hai điểm A và B có hiệu điện thế bằng bao nhiêu nếu một điện tích q = 1 μC thu được năng lượng 2.10^-4J khi đi từ A đến B?",
        options: ["100 V.", "200 V.", "300 V.", "500 V."],
        correct: "200 V.",
        image: "",
        slove_image: "Ly/31.png",
    },
    {
        id: "30",
        question: "Những đường sức điện nào vẽ ở dưới đây là đường sức của điện trường đều",
        options: ["Hình 1.", "Hình 4.", "Hình 2.", "Hình 3."],
        correct: "Hình 1.",
        image: "Ly/32.png",
        slove_image: "Ly/33.png",
    },
    // DE 2
    {
        id: "31",
        question: "Về sự tương tác điện, trong các nhận định dưới đây, nhận định sai là",
        options: [
            "Các điện tích cùng loại thì đẩy nhau.",
            "Các điện tích khác loại thì hút nhau.",
            "Hai thanh nhựa giống nhau, sau khi cọ xát với len dạ, nếu đưa lại gần thì chúng sẽ hút nhau.",
            "Hai thanh thủy tinh sau khi cọ xát vào lụa, nếu đưa lại gần nhau thì chúng sẽ đẩy nhau.",
        ],
        correct: "Hai thanh nhựa giống nhau, sau khi cọ xát với len dạ, nếu đưa lại gần thì chúng sẽ hút nhau.",
        image: "",
        slove_image: "Ly/37.png",
    },
    {
        id: "32",
        question:
            "Lực lạ thực hiện một công là 840mJ khi dịch chuyển một lượng điện tích 3,5.10^-2C giữa hai cực bên trong nguồn điện. Tính suất điện động của nguồn điện này?",
        options: ["9 V.", "12 V.", "24 V.", "6 V."],
        correct: "24 V.",
        image: "",
        slove_image: "Ly/38.png",
    },
    {
        id: "33",
        question: "Nhận xét không đúng về điện môi là:",
        options: [
            "Điện môi là môi trường cách điện.",
            "Hằng số điện môi của chân không bằng 1.",
            "Hằng số điện môi của một môi trường cho biết lực tương tác giữa các điện tích trong môi trường đó nhỏ hơn so với khi chúng đặt trong chân không bao nhiêu lần.",
            "Hằng số điện môi có thể nhỏ hơn 1.",
        ],
        correct: "Hằng số điện môi có thể nhỏ hơn 1.",
        image: "",
        slove_image: "Ly/39.png",
    },
    {
        id: "34",
        question:
            "Nếu trong thời gian ∆t = 0,1s đầu có điện lượng 0,5 C và trong thời gian ∆t' = 0,1s tiếp theo có điện lượng 0,1C chuyển qua tiết diện của vật dẫn thì cường độ dòng điện trong cả hai khoảng thời gian đó là",
        options: ["6 A.", "3 A.", "4 A.", "2 A."],
        correct: "3 A.",
        image: "",
        slove_image: "Ly/40.png",
    },
    {
        id: "35",
        question: "Hiện tượng đoản mạch của nguồn điện xảy ra khi",
        options: [
            "Sử dụng các dây dẫn ngắn để mắc mạch điện.",
            "Nối hai cực của một nguồn điện bằng dây dẫn có điện trở rất nhỏ.",
            "Không mắc cầu chì cho một mạch điện kín.",
            "Dùng pin hay acquy để mắc một mạch điện kín.",
        ],
        correct: "Nối hai cực của một nguồn điện bằng dây dẫn có điện trở rất nhỏ.",
        image: "",
        slove_image: "Ly/41.png",
    },
    {
        id: "36",
        question: "Hai điện tích điểm trái dấu có cùng độ lớn 10^-4C đặt cách nhau 1m trong parafin có điện môi bằng 2 thì chúng",
        options: ["Hút nhau một lực 4,5 N.", "Hút nhau một lực 45 N.", "Đẩy nhau một lực 45 N.", "Đẩy nhau một lực 4,5 N."],
        correct: "Hút nhau một lực 45 N.",
        image: "",
        slove_image: "Ly/42.png",
    },
    {
        id: "37",
        question: "Một điện trở R = 4Ω mắc vào nguồn có Điện trở trong của nguồn và hiệu điện thế giữa hai đầu điện trở R là",
        options: ["1Ω; 1,2V.", "2Ω; 4,5V.", "1Ω; 3V.", "2Ω; 3V."],
        correct: "2Ω; 3V.",
        image: "",
        slove_image: "Ly/43.png",
    },
    {
        id: "38",
        question:
            "Hai điện tích điểm có độ lớn bằng nhau đặt trong chân không cách nhau một khoảng r = 2cm. Lực đẩy giữa chúng là F = 1,6.10^-4N. Độ lớn của hai điện tích đó là",
        options: ["q1 = q2 = 2,67.10^-7C.", "q1 = q2 = 2,67.10^-7µC.", "q1 = q2 = 2,67.10^-9µC.", "q1 = q2 = 2,67.10^-9C."],
        correct: "q1 = q2 = 2,67.10^-9C.",
        image: "",
        slove_image: "Ly/44.png",
    },
    {
        id: "39",
        question:
            "Hai điện tích điểm q1 và q2, đặt cách nhau một khoảng r = 20cm trong chân không, tương tác lên nhau một lực hút F = 3,6.10^-4N. Cho biết điện tích tổng cộng của hai điện tích là Q = 6.10^-8C. Điện tích q1 và q2 có giá trị lần lượt là",
        options: [
            "q1 = -1.10^-8C và q2 = -6.10^-8C.",
            "q1 = -4.10^-8C và q2 = -2.10^-8C.",
            "q1 = -2.10^-8C và q2 = 9.10^-8C.",
            "q1 = 2.10^-8C và q2 = 8.10^-8C.",
        ],
        correct: "q1 = -2.10^-8C và q2 = 9.10^-8C.",
        image: "",
        slove_image: "Ly/45.png",
    },
    {
        id: "40",
        question:
            "Một tụ điện được tích điện bằng một hiệu điện thế 10 V thì năng lượng của tụ là 10 mJ. Nếu muốn năng lượng của tụ là 22,5 mJ thì hai bản tụ phải có hiệu điện thế là",
        options: ["15 V.", "7,5 V.", "20 V.", "40 V."],
        correct: "15 V.",
        image: "",
        slove_image: "Ly/46.png",
    },
    {
        id: "41",
        question: "Điều kiện để có dòng điện là",
        options: [
            "Cần duy trì hiệu điện thế giữa hai đầu vật dẫn.",
            "Có điện tích tự do trong vật dẫn.",
            "Có hiệu điện thế và điện tích tự do.",
            "Có nguồn điện.",
        ],
        correct: "Cần duy trì hiệu điện thế giữa hai đầu vật dẫn.",
        image: "",
        slove_image: "Ly/47.png",
    },
    {
        id: "42",
        question: "Thế năng của một electron tại điểm M trong điện trường của một điện tích điểm là -3,2.10^-19 (J). Điện thế tại điểm M là",
        options: ["3,2 (V).", "-3 (V).", "2 (V).", "3 (V)."],
        correct: "2 (V).",
        image: "",
        slove_image: "Ly/48.png",
    },
    {
        id: "43",
        question: "Câu phát biểu nào sau đây chưa đúng?",
        options: [
            "Qua mỗi điểm trong điện trường chỉ vẽ được một đường sức.",
            "Các đường sức của điện trường không cắt nhau.",
            "Đường sức của điện trường bao giờ cũng là đường thẳng.",
            "Đường sức của điện trường tĩnh không khép kín.",
        ],
        correct: "Đường sức của điện trường bao giờ cũng là đường thẳng.",
        image: "",
        slove_image: "Ly/49.png",
    },

    {
        id: "44",
        question: "Hình vẽ nào sau đây là đúng khi vẽ đường sức điện của một điện tích dương?",
        options: ["Hình 1.", "Hình 2.", "Hình 3.", "Hình 4."],
        correct: "Hình 3.",
        image: "Ly/35.png",
        slove_image: "Ly/50.png",
    },
    {
        id: "45",
        question: "Nếu khoảng cách từ điện tích nguồn tới điểm đang xét tăng 2 lần thì cường độ điện trường",
        options: ["Giảm 2 lần.", "Tăng 2 lần.", "Giảm 4 lần.", "Tăng 4 lần."],
        correct: "Giảm 4 lần.",
        image: "",
        slove_image: "Ly/51.png",
    },
    {
        id: "46",
        question:
            "Công của lực điện trường dịch chuyển một điện tích -2µC ngược chiều một đường sức trong một điện trường đều 1000 V/m trên quãng đường dài 1 m là",
        options: ["2000 J.", "-2000 J.", "2 mJ.", "-2 mJ."],
        correct: "2 mJ.",
        image: "",
        slove_image: "Ly/52.png",
    },
    {
        id: "47",
        question: "Mối liên hệ giữa hiệu điện thế UMN và hiệu điện thế UMN",
        options: ["UMN = UNM.", "UMN = -UNM.", "UMN = 1/UNM.", "UMN = -1/UNM."],
        correct: "UMN = -UNM.",
        image: "",
        slove_image: "Ly/53.png",
    },
    {
        id: "48",
        question:
            "Một vòng tròn tâm O nằm trong điện trường của một điện tích điểm Q. M và N là hai điểm trên vòng tròn đó. Gọi AM1N, AM2N và AMN là công của lực điện tác dụng lên điện tích điểm q trong các dịch chuyển dọc theo cung M1N, M2N và dây cung MN thì",
        options: ["AM1N < AM2N", "AMN nhỏ nhất.", "AM2N lớn nhất.", "AM1N = AM2N = AMN."],
        correct: "AMN nhỏ nhất.",
        image: "Ly/36.png",
        slove_image: "Ly/54.png",
    },
    {
        id: "49",
        question:
            "Một điện tích điểm dương Q trong chân không gây ra tại điểm M cách điện tích một khoảng r = 30cm, một điện trường có cường độ E = 3000 V/m. Độ lớn điện tích Q là",
        options: ["Q = 3.10^-6 (C).", "Q = 3.10^-7 (C).", "Q = 3.10^-5 (C).", "Q = 3.10^-8 (C)."],
        correct: "Q = 3.10^-8 (C).",
        image: "",
        slove_image: "Ly/55.png",
    },
    {
        id: "50",
        question: "Chọn một đáp án đúng:",
        options: [
            "Điện trở dây dẫn bằng kim loại giảm khi nhiệt độ tăng.",
            "Dòng điện trong kim loại là dòng chuyển dời của các electron.",
            "Dòng điện trong kim loại là dòng chuyển dời có hướng của các ion.",
            "Kim loại dẫn điện tốt vì mật độ electron tự do trong kim loại lớn.",
        ],
        correct: "Dòng điện trong kim loại là dòng chuyển dời của các electron.",
        image: "",
        slove_image: "Ly/56.png",
    },
    {
        id: "51",
        question: "Biết hiệu điện thế UMN = 8 (V). Hỏi đẳng thức nào dưới đây chắc chắn đúng?",
        options: ["VM = 8 (V).", "VN = 8 (V).", "VM - VN = 8 (V).", "VN - VM = 8 (V)."],
        correct: "VM - VN = 8 (V).",
        image: "",
        slove_image: "Ly/57.png",
    },
    {
        id: "52",
        question:
            "Hai điện tích q1 = 5.10^-9C và q2 = -5.10^-9C đặt tại hai điểm cách nhau 10 cm trong chân không. Độ lớn cường độ điện trường tại điểm nằm trên đường thẳng đi qua hai điện tích và cách đều hai điện tích là:",
        options: ["18000 V/m.", "36000 V/m.", "1800 V/m.", "0 V/m."],
        correct: "0 V/m.",
        image: "",
        slove_image: "Ly/58.png",
    },
    {
        id: "53",
        question:
            "Trong một mạch điện gồm một pin có suất điện động 1,5 V và điện trở trong 0,5 (Ω) nối với mạch ngoài là một điện trở 2,5 (Ω). Cường độ dòng điện trong toàn mạch là",
        options: ["3 A.", "0,6 A.", "0,5 A.", "2 A."],
        correct: "0,5 A.",
        image: "",
        slove_image: "Ly/59.png",
    },
    {
        id: "54",
        question: "Cho đoạn mạch điện trở 10 Ω, hiệu điện thế 2 đầu mạch là 20 V. Trong 1 phút điện năng tiêu thụ của mạch là",
        options: ["2,4 kJ.", "40 J.", "24 kJ.", "120 J."],
        correct: "2,4 kJ.",
        image: "",
        slove_image: "Ly/60.png",
    },
    {
        id: "55",
        question: "Công của lực điện tác dụng lên điện tích điểm q khi di chuyển từ điểm M đến điểm N trong điện trường",
        options: [
            "Tỉ lệ thuận với chiều dài đường đi MN.",
            "Tỉ lệ thuận với độ lớn điện tích.",
            "Tỉ lệ thuận với thời gian di chuyển.",
            "Tỉ lệ thuận với tốc độ dịch chuyển.",
        ],
        correct: "Tỉ lệ thuận với độ lớn điện tích.",
        image: "",
        slove_image: "Ly/61.png",
    },
    {
        id: "56",
        question:
            "Quả cầu nhỏ khối lượng m = 25g, mang điện tích q = 2,5.10^-7C được treo bởi một sợi dây không dãn, khối lượng không đáng kể và đặt vào trong một điện trường đều với cường độ điện trường →E có phương nằm ngang và có độ lớn E = 10^6 V/m. Lấy g = 10 m/s^2. Góc lệch của dây treo so với phương thẳng đứng là",
        options: ["30°.", "45°.", "60°.", "75°."],
        correct: "45°.",
        image: "",
        slove_image: "Ly/62.png",
    },
    {
        id: "57",
        question: "Một tụ có điện dung 2µF. Khi đặt một hiệu điện thế 4V vào hai bản của tụ điện thì tụ tích được một điện lượng là",
        options: ["2.10^-6C.", "16.10^-6C.", "4.10^-6C.", "8.10^-6C."],
        correct: "8.10^-6C.",
        image: "",
        slove_image: "Ly/63.png",
    },
    {
        id: "58",
        question: "Nếu điện tích dịch chuyển trong điện trường sao cho thế năng của nó tăng thì công của của lực điện trường",
        options: ["Âm.", "Dương.", "Bằng không.", "Tăng."],
        correct: "Âm.",
        image: "",
        slove_image: "Ly/64.png",
    },
    {
        id: "59",
        question:
            "Trong một điện trường đều, nếu trên một đường sức, giữa hai điểm cách nhau 4 cm có hiệu điện thế 10 V thì giữa hai điểm cách nhau 6 cm có hiệu điện thế là",
        options: ["8 V.", "10 V.", "15 V.", "22,5 V."],
        correct: "15 V.",
        image: "",
        slove_image: "Ly/65.png",
    },
    {
        id: "60",
        question:
            "Nối hai bản tụ điện phẳng với hai cực của nguồn một chiều, sau đó ngắt tụ ra khỏi nguồn rồi đưa vào giữa hai bản một chất điện môi có hằng số điện môi ε thì điện dung C và hiệu điện thế giữa hai bản tụ sẽ:",
        options: ["C tăng, U tăng.", "C tăng, U giảm.", "C giảm, U giảm.", "C giảm, U tăng."],
        correct: "C tăng, U giảm.",
        image: "",
        slove_image: "Ly/66.png",
    },
];
