const Ly = [
    {
        id: "0",
        question: "Chọn câu đúng.",
        options: [
            "Cường độ dòng điện cho biết độ mạnh hay yếu của dòng điện.",
            "Khi nhiệt độ tăng thì cường độ dòng điện tăng.",
            "Cường độ dòng điện qua một đoạn mạch tỉ lệ nghịch với điện lượng dịch chuyển qua đoạn mạch.",
            "Dòng điện là dòng các electron dịch chuyển có hướng.",
        ],
        correct: "Cường độ dòng điện cho biết độ mạnh hay yếu của dòng điện.",
        image: "",
        slove_image: "Ly/1.png",
    },
    {
        id: "1",
        question: "Suất điện động của một acquy là 2 V, lực lạ đã thực hiện một công là 6 mJ. Lượng điện tích dịch chuyển khi đó là",
        options: ["18.10^–3 C.", "3.10^–3 C.", "0,5.10^–3 C.", "1,8.10^–3 C."],
        correct: "3.10^–3 C.",
        image: "",
        slove_image: "Ly/2.png",
    },
    {
        id: "2",
        question:
            "Đường đặc tuyến Vôn - Ampe biểu diễn sự phụ thuộc của cường độ dòng điện qua một điện trở vào hiệu điện thế hai đầu vật dẫn là đường",
        options: ["cong hình elip.", "thẳng.", "hyperbol.", "parabol."],
        correct: "thẳng.",
        image: "",
        slove_image: "Ly/3.png",
    },
    {
        id: "3",
        question:
            "Đặt vào hai đầu một điện trở R = 20 Ω một hiệu điện thế U = 2 V trong khoảng thời gian t = 20 s. Lượng điện tích di chuyển qua điện trở là",
        options: ["q = 4 C.", "q = 1 C.", "q = 2 C.", "q = 5 mC."],
        correct: "q = 2 C.",
        image: "",
        slove_image: "Ly/4.png",
    },
    {
        id: "4",
        question: "Dòng điện chạy qua dây dẫn của một camera có cường độ 50 μA. Số electron chạy qua dây dẫn mỗi giây là",
        options: ["3,75.10^14 hạt.", "3,35.10^14 hạt.", "3,125.10^14 hạt.", "50.10^15 hạt."],
        correct: "3,125.10^14 hạt.",
        image: "",
        slove_image: "Ly/5.png",
    },
    {
        id: "5",
        question: "Hệ số nhiệt điện trở α của kim loại phụ thuộc vào yếu tố nào sau đây?",
        options: [
            "Khoảng nhiệt độ và chế độ gia công của vật liệu đó.",
            "Độ sạch của kim loại và chế độ gia công của vật liệu đó.",
            "Độ sạch của kim loại.",
            "Khoảng nhiệt độ, độ sạch của kim loại và chế độ gia công của vật liệu đó.",
        ],
        correct: "Khoảng nhiệt độ, độ sạch của kim loại và chế độ gia công của vật liệu đó.",
        image: "",
        slove_image: "Ly/6.png",
    },
    {
        id: "6",
        question:
            "Cho mạch điện như hình vẽ. Suất điện động E = 28V, điện trở trong r = 2Ω, R = 5Ω. Độ lớn của cường độ dòng điện trong mạch chính là",
        options: ["2 A.", "3 A.", "4 A.", "5 A."],
        correct: "4 A.",
        image: "Ly/7.png",
        slove_image: "Ly/8.png",
    },
    {
        id: "7",
        question: "Câu nào sau đây là sai?",
        options: [
            "Suất điện động của nguồn điện là đại lượng đặc trưng cho khả năng sinh công của nguồn điện.",
            "Đơn vị công cũng là đơn vị suất điện động.",
            "Suất điện động của nguồn điện bằng công để di chuyển điện tích dương 1 C từ cực âm đến cực dương bên trong nguồn.",
            "Suất điện động được đo bằng thương số giữa công A của lực lạ để di chuyển một điện tích dương từ cực âm đến cực dương bên trong nguồn điện và độ lớn q của điện tích đó.",
        ],
        correct: "Suất điện động của nguồn điện bằng công để di chuyển điện tích dương 1 C từ cực âm đến cực dương bên trong nguồn.",
        image: "",
        slove_image: "Ly/9.png",
    },
    {
        id: "8",
        question: "Một đoạn mạch tiêu thụ có công suất 100 W, trong 10 phút nó tiêu thụ một năng lượng",
        options: ["2000 J.", "5 J.", "120 kJ.", "60 kJ."],
        correct: "60 kJ.",
        image: "",
        slove_image: "Ly/10.png",
    },
    {
        id: "9",
        question: "Công suất định mức của các dụng cụ điện là",
        options: [
            "công suất lớn nhất mà dụng cụ đó có thể đạt được.",
            "công suất tối thiểu mà dụng cụ đó có thể đạt được.",
            "công suất đạt được khi nó hoạt động bình thường.",
            "công suất trung bình của dụng cụ đó.",
        ],
        correct: "công suất đạt được khi nó hoạt động bình thường.",
        image: "",
        slove_image: "Ly/11.png",
    },
    {
        id: "10",
        question:
            "Hai điện tích điểm nằm yên trong chân không tương tác với nhau bằng một lực F. Thay đổi các điện tích thì lực tương tác đổi chiều nhưng độ lớn không đổi. Hỏi các yếu tố trên thay đổi như thế nào?",
        options: ["Đổi dấu q1, không thay đổi q2.", "Tăng giảm sao cho q1 + q2 không đổi.", "Đổi dấu q1 và q2.", "Tăng gấp đôi q1 giảm 2 lần q2."],
        correct: "Đổi dấu q1, không thay đổi q2.",
        image: "",
        slove_image: "Ly/12.png",
    },
    {
        id: "11",
        question: "Một dây dẫn kim loại có điện lượng q = 30 C đi qua tiết diện của dây trong 2 giây. Số electron qua tiết diện của dây trong 1s là",
        options: ["9,375.10^19 hạt.", "15,625.10^17 hạt.", "9,375.10^18 hạt.", "3,125.10^18 hạt."],
        correct: "9,375.10^19 hạt.",
        image: "",
        slove_image: "Ly/13.png",
    },
    {
        id: "12",
        question:
            "Đồ thị biểu diễn độ lớn lực tương tác giữa hai điện tích điểm trong chân không phụ thuộc vào khoảng cách r được cho như hình vẽ bên. Tính tỉ số F2/F1?",
        options: ["2.", "3.", "4.", "5."],
        correct: "4.",
        image: "",
        slove_image: "Ly/14.png",
    },
    {
        id: "13",
        question: "Công thức tính điện năng tiêu thụ của một đoạn mạch là",
        options: ["A = U.I.t.", "A = 3 Đề thi Học kì 2 Vật lí 11 Kết nối tri thức (có đáp án + ma trận)It.", "A = I.t / U.", "A = U.I / t."],
        correct: "A = U.I.t.",
        image: "",
        slove_image: "Ly/15.png",
    },
    {
        id: "14",
        question:
            "Hai điện tích điểm cùng độ lớn 10^-4C đặt trong chân không, để tương tác nhau bằng lực có độ lớn 10^-3C thì chúng phải đặt cách nhau",
        options: ["30000 m.", "300 m.", "90000 m.", "900 m."],
        correct: "300 m.",
        image: "",
        slove_image: "Ly/16.png",
    },
    {
        id: "15",
        question: "Thế năng của một electron tại điểm M trong điện trường của một điện tích điểm là -4,8.10^-19 (J). Điện thế tại M là",
        options: ["3,2 V.", "-3 V.", "2 V.", "3 V."],
        correct: "3 V.",
        image: "",
        slove_image: "Ly/17.png",
    },
    {
        id: "16",
        question: "Một tụ điện có điện dung là bao nhiêu thì tích lũy một năng lượng 0,015 J dưới một hiệu điện thế 5 V:",
        options: ["1,2.10^-2 F.", "1,2.10^-4 F.", "1,2.10^-3 F.", "12.10^-3 F."],
        correct: "1,2.10^-3 F.",
        image: "",
        slove_image: "Ly/18.png",
    },
    {
        id: "17",
        question:
            "Người ta treo hai quả cầu nhỏ khối lượng bằng nhau bằng hai sợi dây nhẹ có độ dài ℓ như nhau. Cho chúng nhiễm điện bằng nhau thì chúng đẩy nhau và cân bằng khi mỗi dây treo hợp với phương thẳng đứng một góc 15°. Tính sức căng của dây treo. Lấy g = 10 m/s^2.",
        options: ["520.10^-5 N.", "103,5.10^-5 N.", "261.10^-5 N.", "743.10^-5 N."],
        correct: "103,5.10^-5 N.",
        image: "Ly/19.png",
        slove_image: "Ly/20.png",
    },
    {
        id: "18",
        question: "Độ lớn cường độ điện trường tại một điểm gây bởi một điện tích điểm không phụ thuộc",
        options: [
            "độ lớn điện tích thử.",
            "độ lớn điện tích đó.",
            "khoảng cách từ điểm đang xét đến điện tích đó.",
            "hằng số điện môi của của môi trường.",
        ],
        correct: "độ lớn điện tích thử.",
        image: "",
        slove_image: "Ly/21.png",
    },
    {
        id: "19",
        question:
            "Một electron chuyển động dọc theo đường sức của một điện trường đều. Cường độ điện trường E = 200 (V/m) vận tốc ban đầu của electron là 3.10^5(m/s). Tại lúc vận tốc bằng không thì nó đã đi được đoạn đường bao nhiêu?",
        options: ["5,12 (mm).", "2,56 (mm).", "1,28 (mm).", "10,24 (mm)."],
        correct: "1,28 (mm).",
        image: "",
        slove_image: "Ly/22.png",
    },
    {
        id: "20",
        question: "Khi độ lớn điện tích thử đặt tại một điểm tăng lên gấp đôi thì điện thế tại điểm đó",
        options: ["không đổi.", "tăng gấp đôi.", "giảm một nửa.", "tăng gấp 4."],
        correct: "không đổi.",
        image: "",
        slove_image: "Ly/23.png",
    },
    {
        id: "21",
        question:
            "Nếu đặt vào hai đầu tụ một hiệu điện thế 4 V thì tụ tích được một điện lượng 2µC. Nếu đặt vào hai đầu tụ một hiệu điện thế 10 V thì tụ tích được một điện lượng",
        options: ["50µC.", "1µC.", "5µC", "0,8µC."],
        correct: "5µC",
        image: "",
        slove_image: "Ly/24.png",
    },
    {
        id: "22",
        question:
            "Cường độ điện trường gây ra bởi điện tích Q = 5.10^-9C, tại một điểm trong chân không cách điện tích một khoảng 30 cm có độ lớn là",
        options: ["E = 0,450 (V/m).", "E = 0,225 (V/m).", "E = 500 (V/m).", "E = 2250 (V/m)."],
        correct: "E = 500 (V/m).",
        image: "",
        slove_image: "Ly/25.png",
    },
    {
        id: "23",
        question: "Công của lực điện trường tác dụng lên một điện tích chuyển động từ M đến N sẽ",
        options: [
            "chỉ phụ thuộc vào vị trí điểm M không phụ thuộc vào vị trí điểm N.",
            "phụ thuộc vào hình dạng của đường đi MN.",
            "phụ thuộc vị trí các điểm M và N chứ không phụ thuộc vào đoạn MN dài hay ngắn.",
            "càng lớn khi đoạn đường MN càng dài.",
        ],
        correct: "phụ thuộc vị trí các điểm M và N chứ không phụ thuộc vào đoạn MN dài hay ngắn.",
        image: "",
        slove_image: "Ly/26.png",
    },
    {
        id: "24",
        question:
            "Ở sát mặt Trái Đất, vectơ cường độ điện trường hướng thẳng đứng từ trên xuống dưới và có độ lớn vào khoảng 150 V/m. Tính hiệu điện thế giữa một điểm ở độ cao 2,4 m và mặt đất.",
        options: ["720 (V).", "360 (V).", "120 (V).", "750 (V)."],
        correct: "360 (V).",
        image: "",
        slove_image: "Ly/27.png",
    },
    {
        id: "25",
        question: "Hai tụ điện chứa cùng một lượng điện tích thì",
        options: [
            "chúng phải có cùng điện dung.",
            "hiệu điện thế giữa hai bản của mỗi tụ điện phải bằng nhau.",
            "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản nhỏ hơn.",
            "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản lớn hơn",
        ],
        correct: "tụ có điện dung lớn sẽ có hiệu điện thế giữa hai bản nhỏ hơn.",
        image: "",
        slove_image: "Ly/28.png",
    },
    {
        id: "26",
        question:
            "Hai điện tích q1 = 2.10^-6 C và q2 = -8.10^-6 C lần lượt đặt tại hai điểm A và B với AB = 10 (cm). Xác định điểm M trên đường AB mà tại đó E2 = 4E1",
        options: [
            "M nằm trong AB với AM = 2,5 (cm).",
            "M nằm trong AB với AM = 5 (cm).",
            "M nằm ngoài AB với AM = 2,5 (cm).",
            "M nằm ngoài AB với AM = 5 (cm).",
        ],
        correct: "M nằm ngoài AB với AM = 5 (cm).",
        image: "",
        slove_image: "Ly/29.png",
    },
    {
        id: "27",
        question: "Điều nào sau đây là sai khi nói về cấu tạo của tụ điện?",
        options: [
            "Hai bản của tụ là hai vật dẫn.",
            "Giữa hai bản của tụ có thể là chân không.",
            "Hai bản của tụ cách nhau một khoảng rất lớn.",
            "Giữa hai bản của tụ là điện môi.",
        ],
        correct: "Hai bản của tụ cách nhau một khoảng rất lớn.",
        image: "",
        slove_image: "Ly/30.png",
    },
    {
        id: "29",
        question: "Giữa hai điểm A và B có hiệu điện thế bằng bao nhiêu nếu một điện tích q = 1 μC thu được năng lượng 2.10^-4J khi đi từ A đến B?",
        options: ["100 V.", "200 V.", "300 V.", "500 V."],
        correct: "200 V.",
        image: "",
        slove_image: "Ly/31.png",
    },
    {
        id: "30",
        question: "Những đường sức điện nào vẽ ở dưới đây là đường sức của điện trường đều",
        options: ["Hình 1.", "Hình 4.", "Hình 2.", "Hình 3."],
        correct: "Hình 1.",
        image: "Ly/32.png",
        slove_image: "Ly/33.png",
    },
];
